{{ config(materialized='incremental',
			tags=["nightly"],
			post_hook=[
        after_commit("create index if not exists {{ this.name }}__index_on_order_date on {{ this }} (order_date)"),
        after_commit("create index if not exists {{ this.name }}__index_on_storefront_order_id on {{ this }} (storefront_order_id)"),
        after_commit("create index if not exists {{ this.name }}__index_on_sales_order_quantity on {{ this }} (sales_order_quantity)"),
        after_commit("create index if not exists {{ this.name }}__index_on_originating_line_unit_price on {{ this }} (originating_line_unit_price)"),
        after_commit("create index if not exists {{ this.name }}__index_on_external_oms_id on {{ this }} (external_oms_id)"),
        after_commit("create index if not exists {{ this.name }}__index_on_source on {{ this }} (source)"),
        after_commit("create index if not exists {{ this.name }}__index_on_return_quantity on {{ this }} (return_quantity)"),
        after_commit("create index if not exists {{ this.name }}__index_on_unit_price on {{ this }} (unit_price)"),
        after_commit("create index if not exists {{ this.name }}__index_on_shipping_tax on {{ this }} (shipping_tax)"),
        after_commit("create index if not exists {{ this.name }}__index_on_revenue_shipping on {{ this }} (revenue_shipping)"),
        after_commit("create index if not exists {{ this.name }}__index_on_ship_date on {{ this }} (ship_date)"),
        after_commit("create index if not exists {{ this.name }}__index_on_gross_revenue on {{ this }} (gross_revenue)"),
        after_commit("create index if not exists {{ this.name }}__index_on_discount on {{ this }} (discount)"),
        after_commit("create index if not exists {{ this.name }}__index_on_sales_order_sku on {{ this }} (sales_order_sku)")
      ]

) }}


SELECT 

order_id,
line_item_id,
source,
unit_price,
revenue_tax,
revenue_shipping,
external_oms_id,
internal_shopify_order_id,
order_date,
order_status,
notes,
created_by,
ship_date,
type_,
location_id,
sales_order_sku,
sales_order_quantity,
sales_order_quantity_sum_by_order,
line_item_count_by_order,
origin_order_id,
storefront_order_id,
original_order_id,
billing_email,
billing_first_name,
billing_last_name,
shipping_address1,
shipping_address2,
shipping_city,
shipping_state,
shipping_postalcode,
shipping_country,
billing_address1,
billing_address2,
billing_address3,
billing_city,
billing_country,
billing_postalcode, 
shipping_phone_number,
return_order_id,
return_order_created,
unitprice,
shipping_tax,
return_sku,
orderstatus_name,
receipt_date,
return_order_number,
product_status,
return_quantity,
event_return_quantity,
dw_storefront_created_at, 
amex_amount,
visa_amount,
master_amount,
discover_amount,
ea_cc_amount,
paypal_amount,
shopify_installment_amount,
amazonpay_amount,
gc_amount,
shopnow_credit_amount,
stripe_amount,
klarna_amount,
date_shipped,
shipment_order_number,
freight_cost,
shipment_quantity,
sku,
carrier,
service_level,
tracking_id, 
return_tracking_id,
rma_exchange_order_line_id,
originating_line_unit_price,
originating_revenue_tax,
originating_revenue_shipping,
originating_shipping_tax,
originating_remote_discount,
exch_flow_id,
device_order_placed,
billing_state,
fulfillment_location_id,
order_location_id,
fulfillment_location_name,
fulfillment_location_type,
order_location_name,
order_location_type,
is_shopnow_order,
discount_titles,
discount_descriptions,
discount_codes,
gross_revenue,
returned_revenue,
discount,
user_order_seq,
order_type,
subsequent_order,
markdown,
multi_size_order,
multi_size_style_in_order,
full_price_on_date,
gross_merchandise,
new_vs_repeat,
total_order_payments,
combo_ship_date,
primekey

FROM {{ ref('tf_master_orders_analytics') }}
WHERE source = 'Planner'
      OR (order_location_type = 'Internally Drafted' AND gross_revenue = 0::numeric)

{% if is_incremental() %}
  and order_date > (select max(order_date) from {{ this }})
{% endif %}